services:
  db:
    image: postgres:16
    container_name: "ec-db-container"
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ecommerce_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./docker/db/init:/docker-entrypoint-initdb.d
    #    ports:
    #      - ${DB_PORT}:${DB_PORT}
    expose:
      - ${DB_PORT}
    command: ${DB_CMD}

  backend:
    container_name: "ec-backend-container"
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    env_file:
      - .env
    working_dir: /app
    volumes:
      - "./backend/src:/app/src"
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    entrypoint: ["/app/entrypoint.sh"]
    depends_on:
      - db

  frontend:
    container_name: "ec-frontend-container"
    image: "meal-shaker-frontend-image"
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile.local
    working_dir: /app
    volumes:
      - "./frontend:/app"
    ports:
      - ${NEXT_PUBLIC_PORT}:${NEXT_PUBLIC_PORT}
    tty: true
    env_file:
      - .env
    environment:
      - WATCHPACK_POLLING=true
    command: ${NEXT_PUBLIC_CMD}
    depends_on:
      - "db"


#  https-portal:
#    container_name: "ec-nginx-container"
#    image: steveltn/https-portal:1
#    ports:
#      - '80:80'
#      - '443:443'
#    restart: always
#    environment:
#      DOMAINS: ${HTTP_PORTAL_DOMAIN}
#      STAGE: ${STAGE} # Don't use production until staging works
#    #      CUSTOM_NGINX_DOMAIN_TLD_CONFIG_BLOCK: ${CUSTOM_NGINX_DOMAIN_TLD_CONFIG_BLOCK}
#    volumes:
#      - https-portal-data:/var/lib/https-portal
##      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
##    command: >
##      sh -c "cat /var/lib/https-portal/nginx_custom_config.conf >> /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
#
#volumes:
#  https-portal-data: